### ISSUE TITLE
the ode lstm model?

### ISSUE THREAD

**Issue by chooron** [gauchm/mts-lstm#1]
Could u please provide the code of the ode-lstm model

**Comment by gauchm** [comment]
The ODE-LSTM code is part of the [NeuralHydrology](https://github.com/neuralhydrology/neuralhydrology/) library. You can find the ODE-LSTM code [here](https://github.com/neuralhydrology/neuralhydrology/blob/master/neuralhydrology/modelzoo/odelstm.py).

**Comment by chooron** [comment]
> 

Ohh, thanks! I have found the code in the library
